-- AGUATERO - Suscripciones para el proyecto Supabase NUEVO
-- Ejecutar en Supabase SQL Editor.
-- La service_role y los tokens de Mercado Pago NO van aqui.

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null check (plan in ('mensual','anual')),
  status text not null default 'trial',
  mp_preapproval_id text,
  payer_email text,
  current_period_end timestamptz,
  trial_ends_at timestamptz,
  last_mp_event text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id)
);

create index if not exists subscriptions_mp_preapproval_id_idx
  on public.subscriptions(mp_preapproval_id);

alter table public.subscriptions enable row level security;

drop policy if exists "users can read own subscription" on public.subscriptions;
create policy "users can read own subscription"
on public.subscriptions for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.set_subscriptions_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists trg_subscriptions_updated_at on public.subscriptions;
create trigger trg_subscriptions_updated_at
before update on public.subscriptions
for each row execute function public.set_subscriptions_updated_at();

-- Cada cuenta nueva recibe exactamente 7 dias de prueba, registrados en Supabase.
create or replace function public.crear_trial_aguatero()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.subscriptions (user_id, plan, status, payer_email, trial_ends_at, last_mp_event)
  values (new.id, 'mensual', 'trial', new.email, now() + interval '7 days', 'trial_created')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_auth_user_trial_aguatero on auth.users;
create trigger trg_auth_user_trial_aguatero
after insert on auth.users
for each row execute function public.crear_trial_aguatero();

-- Importante: el frontend no puede insertar/modificar/borrar suscripciones.
-- Las escrituras las realiza Vercel con SUPABASE_SERVICE_ROLE_KEY.
